#!/bin/bash
#SBATCH --job-name="quickscape"
#SBATCH --output="quickscape.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 15:00:00

export LD_PRELOAD=/share/apps/compute/gcc-6.2.0/lib64/libstdc++.so.6

./tests.sh