GIT_HASH=`git rev-parse HEAD`
COMPILE_TIME=`date -u +'%Y-%m-%d %H:%M:%S UTC'`

.PHONY: all

all: fastscape_RB+GPU.exe

fastscape_RB+GPU.exe: fastscape_RB+GPU.cpp
	pgc++ -fast -acc -o fastscape_RB+GPU.exe -ta=tesla,pinned,cc60 -Minfo=accel fastscape_RB+GPU.cpp CumulativeTimer.cpp random.cpp -std=c++11 2>&1 -DGIT_HASH="\"$GIT_HASH\"" -DPGI_WAR

clean:
	rm -rf *.exe