GIT_HASH=`git rev-parse HEAD`
COMPILE_TIME=`date -u +'%Y-%m-%d %H:%M:%S UTC'`

.PHONY: all

all:
	pgc++ -g -o fastscape_RB+GPU.exe -ta=tesla,cc60 -Minfo=accel main.cpp CumulativeTimer.cpp  random.cpp  fastscape_BW.cpp fastscape_BW+P.cpp fastscape_BW+PI.cpp fastscape_RB.cpp fastscape_RB+P.cpp fastscape_RB+PI.cpp fastscape_RB+PQ.cpp fastscape_RB+GPU.cpp fastscape_RB+GPU-graph.cpp -std=c++11 -DGIT_HASH="\"$GIT_HASH\"" -DPGI_WAR

clean:
	rm -rf *.exe